// Copyright © 2018 Ray Johnson <ray.johnson@gmail.com>.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package man

func init() {
	RegisterTemplate("markdown", "_", "md", markdownTemplate)
}

// markdownTemplate is a template what will generate markdown syntax documentation.
const markdownTemplate = `## {{.CommandPath}}

{{ .ShortDescription }}

### Synopsis

{{ .Description }}

{{- if .AllFlags }}

### Options

The following options are supported:

{{ range .AllFlags -}}
* {{ if .Shorthand }}{{ print "-" .Shorthand }}, {{ end -}}{{ print "--" .Name }}
{{- if not .NoOptDefVal }}{{if .ArgHint }}=<{{ .ArgHint }}>{{ else }}=<{{ .DefValue }}>{{ end }}{{ end }}
{{- print " - " .Usage }}
{{ end }}
{{- end }}

{{- if .Environment }}

### Environment

{{ .Environment }}
{{- end }}
{{- if .Files }}

### Files

{{ .Files }}
{{- end }}
{{- if .Bugs }}

### Bugs

{{ .Bugs }}
{{- end }}
{{- if .Examples }}

### Examples

{{ .Examples }}
{{- end }}

### Author
{{- if .Author }}

{{ .Author }}
{{- end }}

Page auto-generated by rayjohnson/cobra-man and spf13/cobra
{{- if .SeeAlsos }}

### See Also

{{- range $index, $element := .SeeAlsos}}
* [{{ $element.CmdPath }}]({{ $element.CmdPath | underscoreify }}.md)
{{- end }}
{{- end }}

[//]: # ( This file auto-generated by github.com/rayjohnson/cobra-man )
`
