package man

const defaultManTemplate = `.TH "{{.CommandPath | dashify | backslashify | upper}}" "{{ .Section }}" "{{.CenterFooter}}" "{{.LeftFooter}}" "{{.CenterHeader}}" 
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH NAME
{{ .CommandPath | dashify | backslashify }}
{{- if .ShortDescription }} - {{ .ShortDescription }}
 {{- end }}
.SH SYNOPSIS
.sp
{{- if .SubCommands }}
{{- range .SubCommands }}
\fB{{ . }}\fR [ flags ]
.br{{ end }}
{{- else }}
\fB{{ .CommandPath }} \fR
{{- range .AllFlags -}}
[{{ if .Shorthand }}\fI{{ print "-" .Shorthand | backslashify }}\fP|{{ end -}}
\fI{{ print "--" .Name | backslashify }}\fP] {{ end }}
{{- if not .NoArgs }}[<args>]{{ end }}
{{- end }}
.SH DESCRIPTION
.PP
{{ .Description }}
{{- if .AllFlags }}
.SH OPTIONS
{{ range .AllFlags -}}
.TP
{{ if .Shorthand }}\fB{{ print "-" .Shorthand | backslashify }}\fP, {{ end -}}
\fB{{ print "--" .Name | backslashify }}\fP{{ if not .NoOptDefVal }} =
{{- if .ArgHint }} <{{ .ArgHint }}>{{ else }} {{ .DefValue }}{{ end }}{{ end }}
{{ .Usage | backslashify }}
{{ end }}
{{- end -}}
{{- if .Environment }}
.SH ENVIRONMENT
.PP
{{ .Environment }}
{{- end }}
{{- if .Files }}
.SH FILES
.PP
{{ .Files }}
{{- end }}
{{- if .Bugs }}
.SH BUGS
.PP
{{ .Bugs }}
{{- end }}
{{- if .Examples }}
.SH EXAMPLES
.PP
{{ .Examples }}
{{- end }}
{{- if .Author }}
.SH AUTHOR
.PP
{{ .Author }}
{{- end }}
{{- if .SeeAlsos }}
.SH SEE ALSO
{{- range .SeeAlsos }}
.BR {{ .CmdPath | dashify | backslashify }} ({{ .Section }})
{{- end }}
{{- end }}
." This file auto-generated by github.com/rayjohnson/cobra-man
`

// MdocManTemplate is a template what will use the mdoc macro package.
const MdocManTemplate = `.\" Man page for {{.CommandPath}}
.Dd {{ .Date.Format "Janurary 2006"}}
.\" TODO: date is not in right format - need: <MonthDay> <year>
.Dt "{{.CommandPath | dashify | backslashify | upper}}" "{{ .Section }}"
./" The Dt macro can take one additonal arg - what does it do?
.Os
.Sh NAME
.Nm {{ .CommandPath | dashify | backslashify }}
{{- if .ShortDescription }}
.Nd {{ .ShortDescription }}
{{- end }}
.Sh SYNOPSIS
{{- if .SubCommands }}
{{- range .SubCommands }}
.Nm {{ . }} Op Fl flags Op args
{{- end }}
{{- else }}
.Nm {{ .CommandPath }}
{{- range .AllFlags -}}
.Op Fl {{ if .Shorthand }}{{ print "-" .Shorthand | backslashify }} | {{ end -}}
{{ print "--" .Name | backslashify }}
{{- end }}
{{ if not .NoArgs }}.Op Fl <args>
{{- end }}
{{- end }}
.Ek
.Sh DESCRIPTION
.Nm
{{ .Description }}
{{- if .AllFlags }}
.Sh OPTIONS
{{ range .AllFlags -}}
.It {{ if .Shorthand }}Fl {{ .Shorthand | backslashify }}, {{ end -}}
Fl {{ print "-" .Name | backslashify }}{{ if not .NoOptDefVal }} Ar
{{- if .ArgHint }}{{ .ArgHint }}{{ else }} {{ .DefValue }}{{ end }}{{ end }}
{{ .Usage | backslashify }}
{{ end }}
{{- end }}
{{- if .Environment }}
.Sh ENVIRONMENT
{{ .Environment }}
{{- end }}
{{- if .Files }}
.Sh FILES
{{ .Files }}
{{- end }}
{{- if .Bugs }}
.Sh BUGS
{{ .Bugs }}
{{- end }}
{{- if .Examples }}
.Sh EXAMPLES
{{ .Examples }}
{{- end }}
{{- if .Author }}
.Sh AUTHOR
{{ .Author }}
{{- end }}
{{- if .SeeAlsos }}
.Sh SEE ALSO
{{- range $index, $element := .SeeAlsos}}
    {{- if $index}} ,{{end}}
    .Xr {{$element.CmdPath}} {{$element.Section}}
{{- end }}
{{- end }}
." This file auto-generated by github.com/rayjohnson/cobra-man
`
