package man

import (
	"strings"
	"text/template"
)

type manTemplate struct {
	separator string
	extension string
	template  *template.Template
}

var templateMap = make(map[string]manTemplate)

// RegisterTemplate takes a template string creates a template for use with CobraMan.  It
// also takes a separator and file extension to be used when generating the file names for
// the generated files.
func RegisterTemplate(name string, separator string, extension string, templateString string) {
	// Build the template
	funcMap := template.FuncMap{
		"upper":         strings.ToUpper,
		"backslashify":  backslashify,
		"dashify":       dashify,
		"underscoreify": underscoreify,
		"simpleToTroff": simpleToTroff,
		"simpleToMdoc":  simpleToMdoc,
	}
	parsedTemplate := template.Must(template.New(name).Funcs(funcMap).Parse(templateString))

	t := manTemplate{
		separator: separator,
		extension: extension,
		template:  parsedTemplate,
	}
	templateMap[name] = t
}

func getTemplate(name string) (string, string, *template.Template) {
	t := templateMap[name]
	return t.separator, t.extension, t.template
}

func init() {
	RegisterTemplate("troff", "-", "use_section", troffManTemplate)
	RegisterTemplate("mdoc", "-", "use_section", MdocManTemplate)
	RegisterTemplate("markdown", "_", "md", MarkdownTemplate)
}

// TroffManTemplate generates a man page with only basic troff macros
const troffManTemplate = `.TH "{{.CommandPath | dashify | backslashify | upper}}" "{{ .Section }}" "{{.CenterFooter}}" "{{.LeftFooter}}" "{{.CenterHeader}}" 
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
." This file auto-generated by github.com/rayjohnson/cobra-man
.SH NAME
{{ .CommandPath | dashify | backslashify }}
{{- if .ShortDescription }} - {{ .ShortDescription }}
 {{- end }}
.SH SYNOPSIS
.sp
{{- if .SubCommands }}
{{- range .SubCommands }}
\fB{{ . }}\fR [ flags ]
.br{{ end }}
{{- else }}
\fB{{ .CommandPath }} \fR
{{- range .AllFlags -}}
[{{ if .Shorthand }}\fI{{ print "-" .Shorthand | backslashify }}\fP|{{ end -}}
\fI{{ print "--" .Name | backslashify }}\fP] {{ end }}
{{- if not .NoArgs }}[<args>]{{ end }}
{{- end }}
.SH DESCRIPTION
.PP
{{ .Description | simpleToTroff }}
{{- if .AllFlags }}
.SH OPTIONS
{{ range .AllFlags -}}
.TP
{{ if .Shorthand }}\fB{{ print "-" .Shorthand | backslashify }}\fP, {{ end -}}
\fB{{ print "--" .Name | backslashify }}\fP{{ if not .NoOptDefVal }} =
{{- if .ArgHint }} <{{ .ArgHint }}>{{ else }} {{ .DefValue }}{{ end }}{{ end }}
{{ .Usage | backslashify }}
{{ end }}
{{- end -}}
{{- if .Environment }}
.SH ENVIRONMENT
.PP
{{ .Environment | simpleToTroff }}
{{- end }}
{{- if .Files }}
.SH FILES
.PP
{{ .Files | simpleToTroff }}
{{- end }}
{{- if .Bugs }}
.SH BUGS
.PP
{{ .Bugs | simpleToTroff }}
{{- end }}
{{- if .Examples }}
.SH EXAMPLES
.PP
{{ .Examples | simpleToTroff }}
{{- end }}
.SH AUTHOR
{{- if .Author }}
{{ .Author }}
{{- end }}
.PP
.SM Page auto-generated by rayjohnson/cobra-man and spf13/cobra
{{- if .SeeAlsos }}
.SH SEE ALSO
{{- range .SeeAlsos }}
.BR {{ .CmdPath | dashify | backslashify }} ({{ .Section }})
{{- end }}
{{- end }}
." This file auto-generated by github.com/rayjohnson/cobra-man
`

// MdocManTemplate is a template what will use the mdoc macro package.
const MdocManTemplate = `.\" Man page for {{.CommandPath}}
.Dd {{ .Date.Format "January 2006"}}
{{ if .CenterHeader -}}
.Dt {{.CommandPath | dashify | backslashify | upper}} \&{{ .Section }} "{{.CenterHeader}}" 
{{- else -}}
.Dt {{.CommandPath | dashify | backslashify | upper}} {{ .Section }}
{{- end }}
./" TODO: The Dt macro can take one additonal arg - what does it do?
.Os
." This file auto-generated by github.com/rayjohnson/cobra-man
.Sh NAME
.Nm {{ .CommandPath | dashify | backslashify }}
{{- if .ShortDescription }}
.Nd {{ .ShortDescription }}
{{- end }}
.Sh SYNOPSIS
{{- if .SubCommands }}
{{- range .SubCommands }}
.Nm {{ . }} Op Fl flags Op args
{{- end }}
{{- else }}
.Nm {{ .CommandPath }}
{{- range .AllFlags }}
.Op Fl {{ if .Shorthand }}{{ .Shorthand | backslashify }} | {{ end -}}
{{ print "-" .Name | backslashify }}
{{- end }}
{{ if not .NoArgs }}.Op Fl <args>
{{- end }}
{{- end }}
.Ek
.Sh DESCRIPTION
.Nm
{{ .Description | simpleToMdoc }}
{{- if .AllFlags }}
.Pp
The options are as follows:
.Pp
.Bl -tag -width Ds -compact
{{ range .AllFlags -}}
.Pp
.It {{ if .Shorthand }}Fl {{ .Shorthand | backslashify }}, {{ end -}}
Fl {{ print "-" .Name | backslashify }}
{{- if not .NoOptDefVal }} Ar {{if .ArgHint }} {{ .ArgHint }}{{ else }} {{ .DefValue }}{{ end }}{{ end }}
{{ .Usage | backslashify }}
{{ end }}
.El
{{- end }}
{{- if .Environment }}
.Sh ENVIRONMENT
{{ .Environment | simpleToMdoc }}
{{- end }}
{{- if .Files }}
.Sh FILES
{{ .Files | simpleToMdoc }}
{{- end }}
{{- if .Bugs }}
.Sh BUGS
{{ .Bugs | simpleToMdoc }}
{{- end }}
{{- if .Examples }}
.Sh EXAMPLES
{{ .Examples | simpleToMdoc }}
{{- end }}
.Sh AUTHOR
{{- if .Author }}
{{ .Author }}
{{- end }}
.sp
Page auto-generated by rayjohnson/cobra-man and spf13/cobra
{{- if .SeeAlsos }}
.Sh SEE ALSO
{{- range $index, $element := .SeeAlsos}}
{{- if $index}} ,{{end}}
.Xr {{$element.CmdPath}} {{$element.Section}}
{{- end }}
{{- end }}
." This file auto-generated by github.com/rayjohnson/cobra-man
`

// MarkdownTemplate is a template what will generate markdown syntax documentation.
const MarkdownTemplate = `## {{.CommandPath}}
<!--- This file auto-generated by github.com/rayjohnson/cobra-man --->

{{ .ShortDescription }}

### Synopsis

{{ .Description }}

{{- if .AllFlags }}

### Options

The following options are supported:

{{ range .AllFlags -}}
* {{ if .Shorthand }}{{ print "-" .Shorthand }}, {{ end -}}{{ print "--" .Name }}
{{- if not .NoOptDefVal }}{{if .ArgHint }}=<{{ .ArgHint }}>{{ else }}=<{{ .DefValue }}>{{ end }}{{ end }}
{{- print " - " .Usage }}
{{ end }}
{{- end }}

{{- if .Environment }}

### Environment

{{ .Environment }}
{{- end }}
{{- if .Files }}

### Files

{{ .Files }}
{{- end }}
{{- if .Bugs }}

### Bugs

{{ .Bugs }}
{{- end }}
{{- if .Examples }}

### Examples

{{ .Examples }}
{{- end }}

### Author
{{- if .Author }}

{{ .Author }}
{{- end }}

Page auto-generated by rayjohnson/cobra-man and spf13/cobra
{{- if .SeeAlsos }}

### See Also

{{- range $index, $element := .SeeAlsos}}
* [{{ $element.CmdPath }}]({{ $element.CmdPath | underscoreify }}.md)
{{- end }}
{{- end }}
`
